// <auto-generated />
using System;
using Infrastructure.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CapFootDatabaseContext))]
    [Migration("20230213221013_AddOneToManyBetweenTournamentAndGroups")]
    partial class AddOneToManyBetweenTournamentAndGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entites.Capgemini", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfTeams")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Capgeminis");

                    b.HasData(
                        new
                        {
                            Id = new Guid("84194159-0a0c-4f7a-b7e5-27023df006ac"),
                            City = "Casablanca",
                            Country = "Morocco",
                            DateCreated = new DateTime(2023, 2, 13, 23, 10, 13, 245, DateTimeKind.Local).AddTicks(5896),
                            DateCreation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2023, 2, 13, 23, 10, 13, 245, DateTimeKind.Local).AddTicks(5972),
                            Name = "TS",
                            NumberOfTeams = 16
                        },
                        new
                        {
                            Id = new Guid("aa7c4614-06e8-450f-bce5-f814c0c874ec"),
                            City = "Rabat",
                            Country = "Morocco",
                            DateCreated = new DateTime(2023, 2, 13, 23, 10, 13, 245, DateTimeKind.Local).AddTicks(6142),
                            DateCreation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2023, 2, 13, 23, 10, 13, 245, DateTimeKind.Local).AddTicks(6146),
                            Name = "TS",
                            NumberOfTeams = 8
                        });
                });

            modelBuilder.Entity("Domain.Entites.CapgeminiTournament", b =>
                {
                    b.Property<Guid>("tournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("capgeminiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("tournamentId", "capgeminiId");

                    b.HasIndex("capgeminiId");

                    b.ToTable("CapgeminiTournaments");
                });

            modelBuilder.Entity("Domain.Entites.Groupe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Domain.Entites.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryOrganisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isFinished")
                        .HasColumnType("bit");

                    b.Property<bool>("isSignUpCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("isStarted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b4f9c70e-26d7-4f47-b47e-aaea4e2704e3"),
                            CountryOrganisation = "Maroc",
                            DateCreated = new DateTime(2023, 2, 13, 23, 10, 13, 246, DateTimeKind.Local).AddTicks(4742),
                            DateModified = new DateTime(2023, 2, 13, 23, 10, 13, 246, DateTimeKind.Local).AddTicks(4784),
                            Name = "Tournoi Ramadan",
                            isFinished = false,
                            isSignUpCompleted = false,
                            isStarted = false
                        });
                });

            modelBuilder.Entity("Domain.Entites.CapgeminiTournament", b =>
                {
                    b.HasOne("Domain.Entites.Capgemini", "capgemini")
                        .WithMany("capgeminiTournament")
                        .HasForeignKey("capgeminiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entites.Tournament", "tournament")
                        .WithMany("capgeminiTournament")
                        .HasForeignKey("tournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("capgemini");

                    b.Navigation("tournament");
                });

            modelBuilder.Entity("Domain.Entites.Groupe", b =>
                {
                    b.HasOne("Domain.Entites.Tournament", null)
                        .WithMany("ListeGroupes")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entites.Capgemini", b =>
                {
                    b.Navigation("capgeminiTournament");
                });

            modelBuilder.Entity("Domain.Entites.Tournament", b =>
                {
                    b.Navigation("ListeGroupes");

                    b.Navigation("capgeminiTournament");
                });
#pragma warning restore 612, 618
        }
    }
}
