name: CapFootAction  CI
on: [push]

jobs:
  DomainLayer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Domain
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core Domain Layer
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  ApplicationLayer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Application
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core Application Layer
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  InfrastructureLayer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infrastructure
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core Infrastrure Layer
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
  PresentationLayer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Presentation
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core Presentation Layer
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "7.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
